-- =============================================
-- Open Shop E-commerce Platform - Oracle Schema
-- V001: System Foundation
-- =============================================

-- =============================================
-- AUDIT LOG TABLE
-- =============================================
CREATE TABLE audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(64) NOT NULL,
    operation_type VARCHAR2(10) NOT NULL CHECK (operation_type IN ('INSERT', 'UPDATE', 'DELETE')),
    record_id VARCHAR2(255) NOT NULL,
    old_values JSON,
    new_values JSON,
    changed_by VARCHAR2(255),
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR2(45),
    user_agent CLOB
);

-- INDEXES for audit_log
CREATE INDEX idx_audit_table_record ON audit_log (table_name, record_id);
CREATE INDEX idx_audit_timestamp ON audit_log (changed_at);
CREATE INDEX idx_audit_user ON audit_log (changed_by);

-- COMMENTS for audit_log
COMMENT ON TABLE audit_log IS 'General audit log for all table operations with JSON search capabilities';
COMMENT ON COLUMN audit_log.old_values IS 'JSON field storing old values for UPDATE/DELETE operations';
COMMENT ON COLUMN audit_log.new_values IS 'JSON field storing new values for INSERT/UPDATE operations';


-- =============================================
-- ORDER NUMBER GENERATION FUNCTION
-- =============================================
CREATE OR REPLACE FUNCTION generate_order_number
RETURN VARCHAR2
IS
    seq_val NUMBER;
    order_date VARCHAR2(8);
BEGIN
    SELECT order_number_seq.NEXTVAL INTO seq_val FROM DUAL;
    SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') INTO order_date FROM DUAL;
    RETURN 'ORD-' || order_date || '-' || LPAD(seq_val, 6, '0');
END generate_order_number;
/
