-- =============================================
-- Open Shop E-commerce Platform - Oracle Schema
-- V001: System Foundation
-- =============================================

-- =============================================
-- TENANT USER SETUP (proxy authentication)
-- =============================================

-- If tenant_password provided: user can log in directly with that password.
-- Otherwise: NO AUTHENTICATION (proxy-only, app_user connects on behalf of tenant).
DECLARE
  v_tenant          VARCHAR2(128) := '${tenant}';
  v_tenant_password VARCHAR2(128) := '${tenant_password}';
  v_exists          NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM dba_users WHERE username = v_tenant;

  IF v_exists = 0 THEN
    IF v_tenant_password IS NOT NULL AND LENGTH(v_tenant_password) > 0 THEN
      EXECUTE IMMEDIATE 'CREATE USER ' || v_tenant || ' IDENTIFIED BY "' || v_tenant_password || '"';
      EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || v_tenant;
    ELSE
      EXECUTE IMMEDIATE 'CREATE USER ' || v_tenant || ' NO AUTHENTICATION';
    END IF;
  ELSE
    -- User already exists — just update authentication
    IF v_tenant_password IS NOT NULL AND LENGTH(v_tenant_password) > 0 THEN
      EXECUTE IMMEDIATE 'ALTER USER ' || v_tenant || ' IDENTIFIED BY "' || v_tenant_password || '"';
      EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || v_tenant;
    ELSE
      EXECUTE IMMEDIATE 'ALTER USER ' || v_tenant || ' NO AUTHENTICATION';
    END IF;
  END IF;
END;
/
-- Allow app_user to proxy into this tenant's schema
DECLARE
  v_tenant VARCHAR2(128) := '${tenant}';
BEGIN
  EXECUTE IMMEDIATE 'ALTER USER ' || v_tenant || ' GRANT CONNECT THROUGH ${app_user}';
END;
/

-- =============================================
-- APP USER PRIVILEGES
-- =============================================
-- Grant app_user full DML access across all tenant schemas so the web server
-- can operate against any tenant without per-table grants.
GRANT CREATE SESSION TO openshop;
GRANT SELECT ANY TABLE TO openshop;
GRANT INSERT ANY TABLE TO openshop;
GRANT UPDATE ANY TABLE TO openshop;
GRANT DELETE ANY TABLE TO openshop;
GRANT EXECUTE ANY PROCEDURE TO openshop;
GRANT SELECT ANY SEQUENCE TO openshop;

-- =============================================
-- AUDIT LOG TABLE
-- =============================================
CREATE TABLE audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(64) NOT NULL,
    operation_type VARCHAR2(10) NOT NULL CHECK (operation_type IN ('INSERT', 'UPDATE', 'DELETE')),
    record_id VARCHAR2(255) NOT NULL,
    old_values JSON,
    new_values JSON,
    changed_by VARCHAR2(255),
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR2(45),
    user_agent CLOB
);

-- INDEXES for audit_log
CREATE INDEX idx_audit_table_record ON audit_log (table_name, record_id);
CREATE INDEX idx_audit_timestamp ON audit_log (changed_at);
CREATE INDEX idx_audit_user ON audit_log (changed_by);

-- COMMENTS for audit_log
COMMENT ON TABLE audit_log IS 'General audit log for all table operations with JSON search capabilities';
COMMENT ON COLUMN audit_log.old_values IS 'JSON field storing old values for UPDATE/DELETE operations';
COMMENT ON COLUMN audit_log.new_values IS 'JSON field storing new values for INSERT/UPDATE operations';


-- =============================================
-- ORDER NUMBER SEQUENCE
-- =============================================
CREATE SEQUENCE order_number_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- =============================================
-- ORDER NUMBER GENERATION FUNCTION
-- =============================================
CREATE OR REPLACE FUNCTION generate_order_number
RETURN VARCHAR2
IS
    seq_val NUMBER;
    order_date VARCHAR2(8);
BEGIN
    SELECT order_number_seq.NEXTVAL INTO seq_val FROM DUAL;
    SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') INTO order_date FROM DUAL;
    RETURN 'ORD-' || order_date || '-' || LPAD(seq_val, 6, '0');
END generate_order_number;
/
